### ISSUE TITLE
[BUG] Cannot use `MetaSignature` namespace as type

### ISSUE THREAD

**Issue by francesco-plt** [uport-project/ethr-did#110]
### Current Behavior

The library cannot be used at its current state. If I try to import it in any typescript project, I get the following error:
`Cannot use MetaSignature namespace as type`
At `node_modules/ethr-did/lib/index.d.ts`. Every occurrence of the `MetaSignature` keywork is marked with the error above. This results in typescript failing build and as a consequence the whole library is unusable.

### Expected Behavior

Just running the code in the README should work without any error.

#### Steps to Reproduce

The following code snippet is enough to produce the error:
``` typescript
import { EthrDID } from 'ethr-did'
// some code
const stockVc = await createVerifiableCredentialJwt(
    payload,
    new EthrDID({
      identifier: issuer.getAddress(),
      privateKey: issuer.getPrivateKey()
    }) as Issuer
  )
// some code
```

**Comment by mirceanis** [comment]
I was not able to reproduce this.
Here is my attempt: https://github.com/mirceanis/ts-ethr-did
Please link to a project where this manifests if the project I linked to doesn't help.

**Comment by mirceanis** [comment]
Did you also try the instructions I left in the readme of that project?

**Comment by francesco-plt** [comment]
Reconfiguring the project with a minimal `tsconfig.json` fixed the issue.
