### ISSUE TITLE
As a EthrDID library user I want it to be updated to support the latest registry contracts

### ISSUE THREAD

**Issue by pelle** [uport-project/ethr-did#12]
The contract address changed so make sure the address and abi is updated.

- [ ] `delegateType` is changed to `bytes32`. Change calls to `addDelegate()` to use the new name and encode it correctly (see tests in ethr-did-resolver for example)
- [ ] `name` is changed to `bytes32` for `setAttribute()` call to use the new encodings as well.

This should match the changes here: https://github.com/uport-project/ethr-did-resolver/pull/4

**Comment by mi-xu** [comment]
Blocked.  Upgrading `ethr-did-registry` from `0.0.8` to `0.1.0` causes the following error when running `yarn test`: `Cannot find module 'ethr-did-resolver' from 'index-test.js'`. The dependency in `node_modules` appears to be missing its `lib` dir, so perhaps the latest release was misconfigured.
