### ISSUE TITLE
Is it planned to add revokeAttribute?

### ISSUE THREAD

**Issue by nikolockenvitz** [uport-project/ethr-did#45]
The `ethr-did-registry` offers a method to revoke an attribute. I do not find a corresponding method here in this implementation. Shouldn't this be added or are there any reasons (apart from no time maybe) why this has not been done yet?

**Comment by mirceanis** [comment]
At the moment there is not enough bandwidth to dedicate to maintaining this library properly.
If you have extra time on your hands, we encourage you to post a PR to fix this issue.

**Comment by nikolockenvitz** [comment]
thx, will do this soon

**Comment by nikolockenvitz** [comment]
I created #46, can you check whether everything is fine?
Thanks
