### ISSUE TITLE
Readme errata

### ISSUE THREAD

**Issue by ilanolkies** [uport-project/ethr-did#49]
Hi team,

The readme states 'An example of a DID document resolved using the Ethr-Did-Resolver:'

```
       type: 'Secp256k1SignatureAuthentication2018',
```

The DID v1.0 states in the specs registry:

```
"type": "EcdsaSecp256k1RecoveryMethod2020",
```

Ref: https://w3c.github.io/did-spec-registries/#ethereumaddress

Is the readme outdated? I'm not sure if this is an error

**Comment by mirceanis** [comment]
It's a bug, but not only in the readme, also in the [ethr-did-resolver](https://github.com/decentralized-identity/ethr-did-resolver/issues/99).
