### ISSUE TITLE
how do i use delegate and signed functions?

### ISSUE THREAD

**Issue by joeg9soft** [uport-project/ethr-did#84]
how do i use delegate and signed functions?
is there any example code or usage?

**Comment by mirceanis** [comment]
There are examples of using the signed functions in the [ERC1056 registry-contract repository](https://github.com/uport-project/ethr-did-registry). If you have questions about that you can continue the discussion in https://github.com/uport-project/ethr-did-registry/issues/48

Can you be more specific about the delegate functions? What do you want to achieve, or what is it that you don't understand?
