### ISSUE TITLE
`did:eth:` vs `did:ethr:` in readme document

### ISSUE THREAD

**Issue by canadaduane** [uport-project/ethr-did#9]
In the example DID document, the DID id value is presented as
```
id:'did:eth:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74',
```

However, later, in the `DID method` subsection, it directs users to prepend `did:ethr:` to an Ethereum address to create a DID under this schema.

Are these in conflict (`did:eth:` vs `did:ethr:`)? If so, which is the correct DID method?

**Comment by localredhead** [comment]
Good catch!  The correct DID method for this is `did:ethr`.  I've updated the example in the documentation https://github.com/uport-project/ethr-did/commit/27ced502b76827961558a89175f8044ef69d2ab7

Where the `eth:did` comes from is for a different DID-resolver that does not support key management called `eth-did-resolver` as opposed to **ethr-did-resolver**.

Check out github.com/uport-project/eth-did-resolver for more information on the `did:eth` method.

**Comment by canadaduane** [comment]
Ok, thanks for the clarification! I'm still a little confused now, however. Are there two completely different Ethereum-based DID specs, one with `did:eth:` and one with `did:ethr:`?

Also, and I think this was just a mistake in your message, but is there also an `eth:did`?
